### ISSUE TITLE
请问下你是怎么调试的啊？

### ISSUE THREAD

**Issue by GanZhiXiong** [hookYuan/usb#2]

**Comment by GanZhiXiong** [comment]
Micro USB 要同时连接USB设备和数据线进行真机调试，需要一个转换器，你用的是什么转换器呢？

**Comment by GanZhiXiong** [comment]
我用的android手机是Micro USB接口，不是Type C，所以不知道有没有可以实现的转换器

**Comment by GanZhiXiong** [comment]
通过WiFi调试解决了，只是WiFi调试有点慢，不知道有没有更好的办法

**Comment by hookYuan** [comment]
手机和电脑可以使用adb连接调试，还可以使用type-c转usb转接器，然后在转接usb扩展器，这样像连接多少usb设备都可以，注意是否是供电的usb扩展器，可能电压不够

**Comment by GanZhiXiong** [comment]
如果手机是micro usb，那么是不是只能通过adb WiFi调试，好像micro usb不能同时连接数据线和扩展的usb

**Comment by hookYuan** [comment]
我之前用过的是一个type-c转usb的转接器，然后在使用一个usb的转接器就可以，有两头都是usb的线，可以直接连接调试，当然如果是开发板，还可以直接用网线连接通过adb调试，比wifi稳定一些。

在 2019-09-18 17:54:08，"干志雄" <notifications@github.com> 写道：


如果手机是micro usb，那么是不是只能通过adb WiFi调试，好像micro usb不能同时连接数据线和扩展的usb

**Comment by GanZhiXiong** [comment]
好的，谢谢你！😃
